### PR TITLE
bcm40181 + zcache fix

### PR DESCRIPTION
**Pull request by blu3bird**
bcm40181 is needed for various wireless chips for instance AP6xxx and zcache is a must have for systems with slow I/O but fast CPU.

### CODE REVIEW

**Comment by blu3bird** [comment]
I also added fbcondecor 0.9.6, which allows us to have nice framebuffer decorations.

**Comment by aloksinha2001** [comment]
Bluebird,
1. You need to help understand - how do we use/test the zcache ability?
   Additionally - please also provide a working .config file, - you can put it under config/ for the time being to be able to test it out...

**Comment by blu3bird** [comment]
Hi,

these are the relevant part's of the config:

```
CONFIG_CLEANCACHE=y
CONFIG_ZCACHE=y
```

Now simply add `zcache` to the kernel boot command line and you are good to go.

To verify it works check dmesg for:

```
zcache: cleancache enabled using kernel transcendent memory and compression buddies
zcache: created ephemeral tmem pool, id=0
```

Note: This only works with cleancache-enabled filesystems, for instance ext4. A new zcache pool will be created for every filesystem you mount(id=0 is the root filesystem) and destroy upon umount:

```
zcache: created ephemeral tmem pool, id=1
EXT4-fs (mtdblock8): mounted filesystem with ordered data mode. Opts: (null)
zcache: destroyed pool id=1
```

**Comment by aloksinha2001** [comment]
Kindly also share the exact boot command line parameter for the .config
file - Thanks.

---

http://www.linkedin.com/profile/view?id=12406006&trk=tab_pro
http://aloksinha2001.blogspot.in

**Pull request merged**
